---

version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-deps
      - run:
          command: |
            ls -la
            python hello-world.py
            echo "The code is okay"
  lint:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - python/install-deps
      - run:
          command: flake8 . --extend-exclude=dist,build --show-source --statistics

workflows:
  main:
    jobs:
      - build-and-test
      - lint
